### PR TITLE
Added more metadata types (number, lookup from db, user list). Refact…

### PR DESCRIPTION
**Pull request by ncortex**
…oring helper class to make easier to add new types. Adding the attributes required and column number. Added spanish location

### CODE REVIEW

**Comment by creecros** [comment]
Thank you for putting forth this work.

Please merge my master into yours, resolve conflicts and then send a new pull request, or update this one.

**Comment by creecros** [comment]
it's showing a bunch of stuff that has already changed, so its tough for me to filter out what has actually changed...You need to merge all the commits from my master that have happened since you forked it, and update your master. This should fix the Pull request.

The conflicts should be easy to resolve.

**Comment by creecros** [comment]
also it won't migrate:
`PHP message: [critical] MetaMagik: Unable to migrate schema for the plugin: MetaMagik => SQLSTATE[HY000]: General error: 1 near "ALTER": syntax error" while reading response header from upstream`

**Comment by ncortex** [comment]
Thank you for making this in first place.
Im not used to git workflow so i miss the merge step before the pull request. I will solve it now.
About the sqlite problem is because im incrementing the size of options field. Im planning to use json inside this field to personalize every type of metadata. There is some reason for keeping so low? 
I think there is no problem in increase it, but in sqlite is necessary to delete the table and recreate it. I can do it if you think its a good idea.

**Comment by creecros** [comment]
No problem, I like what I see. I haven't had a lot of time to focus on this plugin, so this is a great help and addition to current code.

For Sqlite, I would:
* rename old column
* create a new column that replaces it
* copy data from old to new
* delete old

**Comment by creecros** [comment]
(255) is enough?

**Comment by creecros** [comment]
I'm getting a lot of undefinded indexes, warnings, and notices...I'll need to look through this and figure out how to resolve. Give me some time.

**Comment by creecros** [comment]
Apparently I was getting them before...i'll merge and solve before a new release. Thanks for for these updates.

**Comment by creecros** [comment]
@ncortex Ok, i went through and fixed all the php warnings and notices. Also noticed there were issues with List, Radio and Check types, they didn't show up in task modification when set. However, `table` type also has issues, and I am not sure what you were trying to do with that one to fix it. What was the intent of `table`? 

I think it allows me to add a dropdown list based off a table and a key in the database, but it looks like it needs three options, tablename, key, value...not sure what to do to fix this one? 

Here's where I am at on this: https://github.com/creecros/MetaMagik/tree/creecros-patch-2

Also, with these changes, the drag and drop doesn't really jive, so I will need to modify how that works to account for the 3 column placements.

**Comment by creecros** [comment]
nevermind I figured it out...table name, key column, value column. it works now, but not sure why you need key column and value column, as value column is the only one that it is storing. Unless it isn't functioning as intended.

This one is tricky. Normal user is gonna be confused on this one, so will need to explain it somewhere to the user. Putting the wrong things in the options causes issues....

**Pull request merged**
