### PR TITLE
Improves performance to show task footer icons

### PR DESCRIPTION
**Pull request by rafacamargo123**
Adds nb_metadata to TaskFinderModel

### CODE REVIEW

**Comment by rafacamargo123** [comment]
@creecros, this will break the compatibility with your other plugin, Group Assign, because it also overrides the TaskFinderModel.

To keep compatibility, you will have to add this:
https://github.com/creecros/MetaMagik/pull/44/commits/b2637513bea749ec8d8ad196c92616d22869f425#diff-32bfd132dfa83ef47831469eb942804cR27

To the `getExtendedQuery` of the `NewTaskFinderModel` on GroupAssign plugin aswell

**Comment by creecros** [comment]
Since it's extending the task finder model...do i need to add it?

**Comment by rafacamargo123** [comment]
Didn’t get your question. Add it how?

**Comment by creecros** [comment]
Your comment, to add the line to Group_assign.

**Comment by creecros** [comment]
just theory crafting, as i really haven't had time to do this just yet, but what i am saying is, if this NewTaskFinderModel, "extends" the original TaskfinderModel, then instead of doing anything to Group_assign, just keep the compatibility determination in metaMagik, and `if (file_exists('plugins/Group_assign')) ` then `use Kanboard\Plugin\Group_assign\Model\NewTaskFinderModel` instead of `use Kanboard\Model\TaskFinderModel` as the taskfinder you are extending.

**Comment by rafacamargo123** [comment]
Is just as simple as adding that line to the getExtendedQuery. 
When I tested, the model that was “on” was the Group Assign model. Extending the group assign model on metamagik would not solve the compatibility issue because kanboard was  using the Group Assign model. 
The problem with overrides in plugins is that only the “last override” will be used. 
Maybe get the current model before overriding it, then calling their methods on your new class and adding your modifications later may work on this case, but will not make sense on other cases. 

I’m talking about something like this, on plugin.php:

 ```
$oldTaskFinderModel = $this->container['taskFinderModel'];


$this->container['taskFinderModel'] = $this->container->factory(function ($c) {
            return new NewTaskFinderModel($c)
                 ->withTaskFinderModel($oldTaskFinderModel)
});
```
That way we don’t need to extend the NewTaskFinderModel from anything, but we add all methods the original file would have and call (assuming the `withTaskFinderModel` has setted something like `$this->oldTaskFinderModel` variable on the NewTaskFinderModel):
```
function getExtendedQuery() {
    $superResult = $this->oldTaskFinderModel->getExtendedQuery();
    $superResult->myModifications....

    return $superResult;
}
```

If every plugin implements something like that, each plugin will be adding thing up to the modifications that the last plugin loaded did, got it?
It’s like an “extend by hand”
The problem is that you’d still have to write all methods, even those you didn’t change anything, because you are not extending the class, but rewriting it and just calling another class methods

**Comment by rafacamargo123** [comment]
I  wrote this from my phone over midnight and my English is not perfect so I’m sorry if I wrote something that does not make sense... 😂

**Comment by creecros** [comment]
So what I'll do is change the group_assign model, and for MetaMagik, I'll check if Group_assign is installed, and if so, we won't override the model.

**Comment by creecros** [comment]
tested and seems to work with compatibility, unless i'm comletely missing something:
https://github.com/creecros/Group_assign/commit/9afc517aa3e76291ccc7c370cfd4680449ec7a3e

https://github.com/creecros/MetaMagik/commit/0a80d60feb6e15bfff128e81f01a1c5b571d0609

If you don't mind confirming this works, that would be great

**Pull request merged**
